### ISSUE TITLE
Start with ROS

### ISSUE THREAD

**Issue by Kleczyk** [knmlprz/TrailblazerML#83]
# Info 
For the sake of learning and before getting started in ROS, everyone needs to do the task. i encourage you to expand the network of node connections to get a better feel for the topic. We need this before brainstorming. Solutions past in comment .
 
# Description
The goal is to create two ROS 2 nodes, one that publishes data and another that subscribes to it via a topic. The nodes must be correctly built and configured in a package, and their connections should be visualized using `rqt_graph`.

# Tasks
- [x] Create Virtual environment or dual boot system with Ubuntu 22.04
- [x] Install ROS 2 Humble desktop [docs](https://docs.ros.org/en/humble/index.html)
- [x] Create workspace
- [ ] Create the `rover_control` package
- [x] Implement the publisher node (`publisher_node`)
- [ ] Implement the subscriber node (`subscriber_node`)
- [x] Add correct entries to the `setup.py` file
- [x] Build the workspace using `colcon`
- [ ] Visualize node connections using `rqt_graph`

# Task +
- [ ] clone TrailblazerMl repo
- [ ] build it with `colcon`
- [ ] install dependencies with `rosdep` 
- [ ] test repo and visualise the robot model
~~outdated version~~
  ```bash
  ros2 launch trailblazer_bringup controllers_robot.launch.py
  ```
  new version
  ```bash
  ros2 launch trailblazer_bringup urdf_robot.launch.py
  ```
# Resources
[ROS2 humble docs](https://docs.ros.org/en/humble/Installation/Ubuntu-Install-Debs.html)
[ROS2 humble tutorial](https://docs.ros.org/en/humble/Tutorials/Beginner-CLI-Tools/Configuring-ROS2-Environment.html)
[Rosdep humble docs](https://docs.ros.org/en/humble/Tutorials/Intermediate/Rosdep.html)

# Possible Solution

Two nodes:
- **Publisher Node**: Publishes speed as `Float32` every second to the `rover/speed` topic.
- **Subscriber Node**: Subscribes to the `rover/speed` topic and prints received data in the terminal.

Images look this:![Image](https://github.com/user-attachments/assets/15aab4b9-c792-4c9f-893f-a91999a86edf)
![Image](https://github.com/user-attachments/assets/930f095f-9cca-44d9-aedb-744e966fcd24)

![Image](https://github.com/user-attachments/assets/cb01bf8e-9e35-400b-9d21-2509a00ffa16)

 
# Dependencies
- Ubuntu 22.04
- ROS 2 Humble
- Python 3

# Blocked by

**Comment by FWalkowicz** [comment]
@Kleczyk dodaje całe rozwiązanie wraz z przykładowym kodem gdyby ktoś miał jakieś pytania albo mu nie działało.

- [x] Create the `rover_control` package
Jeżeli tutaj nie dodaliśmy w `--dependencies` std_msg musimy to zrobić w pliku `package.xml` żeby poprawnie nam działało.

``` package.xml
<depend>rclpy</depend>  
<depend>std_msgs</depend>
```

``` python
mkdir ROS2

cd ROS2

mkdir src

ros2 pkg create my_robot_controller --build-type ament_python --dependencies rclpy

cd ROS2/src/my_robot_controller/my_robot_controller

touch my_first_node.py
touch my_second_node.py
```
- [x] Implement the publisher node (`publisher_node`)

``` python
import rclpy  
import random  
from std_msgs.msg import String  
from rclpy.node import Node  
  
class SpeedPublisher(Node):  
    def __init__(self):  
        super().__init__('speed_publisher')  
        self.speed_publisher = self.create_publisher(String, '/rover/speed', 10)  
        time_period = 1  
        self.timer = self.create_timer(time_period, self.timer_callback)  
        self.i = 1  
  
    def timer_callback(self):  
        msg = String()  
        msg.data = f'msg: {self.i} - rover speed is : {round(random.random(), 2)}'  
        self.speed_publisher.publish(msg)  
        self.get_logger().info(f'Publishing {msg.data}')  
        self.i += 1  
  
  
def main(args=None):  
    rclpy.init(args=args)  
    node = SpeedPublisher()  
    rclpy.spin(node)  
    rclpy.shutdown()  
  
if __name__ == '__main__':  
    main()
```
- [x] Implement the subscriber node (`subscriber_node`)
``` python
import rclpy  
from std_msgs.msg import String  
from rclpy.node import Node  
  
class SpeedSubscriber(Node):  
    def __init__(self):  
        super().__init__('speed_subscriber')  
        self.create_subscription(  
            String,  
            'rover/speed',  
            self.listener_callback,  
            10  
        )  
  
        self.subscriptions  
  
    def listener_callback(self, msg):  
        self.get_logger().info(f'Subscribed {msg.data}')  
  
  
  
def main(args=None):  
    rclpy.init(args=args)  
    node = SpeedSubscriber()  
    rclpy.spin(node)  
    rclpy.shutdown()  
  
if __name__ == '__main__':  
    main()
```

- [x] Add correct entries to the `setup.py` file

```python
'console_scripts': [  
    "publisher_node = my_robot_controller.my_first_node:main",  
    "subscriber_node = my_robot_controller.my_second_node:main",  
],
```
- [x] Build the workspace using `colcon`
```cmd
colcon build
ros2 run my_robot_controller publisher_node
ros2 run my_robot_controller subscriber_node    
rqt_graph 
```
- [x] Visualize node connections using `rqt_graph`
![image](https://github.com/user-attachments/assets/2e99b581-6c6f-4782-aa2a-6e9ee969b6ad)

**Comment by Kleczyk** [comment]
@kosiarn @Sygnator @kubabartecki @bafaurazan @jKryczka jak tam idzie ?

**Comment by kosiarn** [comment]
@Kleczyk sorki, inżynierka nieco wstrzymała... właśnie instaluję Ubuntu na wirtualce

**Comment by Kleczyk** [comment]
@kosiarn nic się nie dzieje super powodzianka z VM

**Comment by bafaurazan** [comment]
@Kleczyk na linux mint działa wszystko

- [x] Create the `rover_control` package
żeby na linux mint działało sprawdzanie zależności dla ros, trzeba było dać tą komendę

``` bash
sudo apt upgrade

sudo rosdep init
rosdep update
rosdep install --from-paths src --ignore-src -y --skip-keys "fastcdr rti-connext-dds-6.0.1 urdfdom_headers" --os=ubuntu:jammy
```

![image](https://github.com/user-attachments/assets/c4f75718-8570-4505-bbcc-da945eb09cba)

``` bash
mkdir ros2_ws

cd ros2_ws

mkdir src

cd src

ros2 pkg create --build-type ament_python --license Apache-2.0 rover_control

```

- dodawanie zależności do pliku package.xml

``` package.xml
<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>rover_control</name>
  <version>0.0.0</version>
  <description>TODO: Package description</description>
  <maintainer email="rafal@todo.todo">rafal</maintainer>
  <license>Apache-2.0</license>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>std_msgs</exec_depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>

```

- [x] Implement the publisher node (`publisher_node`)

pobranie przykładowego publisher-a i dostosowanie go

``` bash
cd src/rover_control/rover_control/

wget https://raw.githubusercontent.com/ros2/examples/humble/rclpy/topics/minimal_publisher/examples_rclpy_minimal_publisher/publisher_member_function.py
```

``` python
import rclpy
from rclpy.node import Node

from std_msgs.msg import String


class SpeedPublisher(Node):

    def __init__(self):
        super().__init__('speed_publisher')
        self.publisher_ = self.create_publisher(String, 'rover/speed', 10)
        timer_period = 1.0 
        self.timer = self.create_timer(timer_period, self.timer_callback)
        self.i = 0.0

    def timer_callback(self):
        msg = String()
        msg.data = '%.1f' % self.i
        self.publisher_.publish(msg)
        self.get_logger().info('"%s"' % msg.data)
        self.i += 0.1


def main(args=None):
    rclpy.init(args=args)

    my_speed_publisher = SpeedPublisher()

    rclpy.spin(my_speed_publisher)

    my_speed_publisher.destroy_node()
    rclpy.shutdown()


if __name__ == '__main__':
    main()
```

- [x] Implement the subscriber node (`subscriber_node`)

pobranie przykładowego subscriber-a i dostosowanie go

``` bash
cd src/rover_control/rover_control/

wget https://raw.githubusercontent.com/ros2/examples/humble/rclpy/topics/minimal_subscriber/examples_rclpy_minimal_subscriber/subscriber_member_function.py
```

``` python
import rclpy
from rclpy.node import Node

from std_msgs.msg import String


class SpeedSubscriber(Node):

    def __init__(self):
        super().__init__('speed_subscriber')
        self.subscription = self.create_subscription(
            String,
            'rover/speed',
            self.listener_callback,
            10)
        self.subscription 

    def listener_callback(self, msg):
        self.get_logger().info('"%s"' % msg.data)


def main(args=None):
    rclpy.init(args=args)

    my_speed_subscriber = SpeedSubscriber()

    rclpy.spin(my_speed_subscriber)

    my_speed_subscriber.destroy_node()
    rclpy.shutdown()


if __name__ == '__main__':
    main()
```

- [x] Add correct entries to the `setup.py` file

```python
entry_points={
        'console_scripts': [
                'publisher_node = rover_control.publisher_member_function:main',
                'subscriber_node = rover_control.subscriber_member_function:main',
        ],
    },
```
- [x] Build the workspace using `colcon`
```cmd
colcon build
ros2 run rover_control publisher_node
ros2 run rover_control subscriber_node    
rqt_graph 
```
- [x] Visualize node connections using `rqt_graph`

![image](https://github.com/user-attachments/assets/54bf28d9-9727-4326-96b2-c6dff7e6b100)

**Comment by kosiarn** [comment]
![image](https://github.com/user-attachments/assets/67e1bb66-1784-432d-b9d2-45e0cc2522c2)
coś działa aczkolwiek jeśli ktoś wie dlaczego przy każdej nowej instancji terminala muszę robić `source setup.zsh` paczki żeby ros ją widział przy `ros2 run` to byłbym wdzięczny za podzielenie się wiedzą :))))

**Comment by ZegarkOOO** [comment]
![Image](https://github.com/user-attachments/assets/0070baaa-fbc8-413f-980c-1e6a7ad518fa)

**Comment by DamianKobylinski** [comment]
# Solution

## Task

### Image

Solution was made by using ``distrobox``. Container image is a basic ``ubuntu:22.04`` Ubuntu image.

<img width="229" height="199" alt="Image" src="https://github.com/user-attachments/assets/52344d9f-a832-481f-9540-6b37ad0ebd33" />

### Workspace with package 

<img width="806" height="878" alt="Image" src="https://github.com/user-attachments/assets/162569b5-dd2f-4894-9baf-97e6dd49adf5" />

### Nodes

<img width="1838" height="632" alt="Image" src="https://github.com/user-attachments/assets/1efe8c81-e276-43bf-a10c-a5dd1b92aad1" />

This is a @FWalkowicz code - Thanks Filip! This accelerated the completion of the task.

### Result 

<img width="1919" height="1032" alt="Image" src="https://github.com/user-attachments/assets/81172e2f-6126-4953-af59-8f93e1edb05a" />

 ## Task+

<img width="1919" height="1032" alt="Image" src="https://github.com/user-attachments/assets/0093152a-c750-4463-ac6d-f5c4eae98be7" />
