### ISSUE TITLE
Research of CI/CD, tests

### ISSUE THREAD

**Issue by Kleczyk** [knmlprz/TrailblazerML#84]
# Description
The goal of this is to review new techniques for improving the entire process, from task planning in Kanban, creating a branch, coding, committing, testing, merging, testing again, deploying to the platform, and then maintaining it in operation.

# Tasks
What the presentation should include:
- [ ] ROS 2 Humble in Docker (and its automation)
- [ ] Github Actions (from code formatting to automated tests)
- [ ] Test scripts in ROS so that everyone can test

What it must include:
- [ ] A brief introduction to what this field is and what it offers us
- [ ] Description of the technologies
- [ ] Advantages and disadvantages of the solutions (preferably in a table)
- [ ] Opinion on which will be the best for us, considering:
	- [ ] Difficulty of implementation
	- [ ] Benefits
	- [ ] Scalability
	- [ ] Future usage

# Dependencies

- ROS 2 Humble
- Python 3
- git xd
