### ISSUE TITLE
Research of Route mapping

### ISSUE THREAD

**Issue by Kleczyk** [knmlprz/TrailblazerML#85]
# Description
The goal of this is to review new techniques for path planning based on collected data. I would focus on redundant solutions where if one system fails, we can still determine the path. There is also the possibility of purchasing new types of sensors.

# Tasks
What the presentation should include:
- [ ] Algorithms working on point clouds
- [ ] Algorithms working on GPS with an accuracy of up to 5 cm
- [ ] Algorithms working on LiDAR
- [ ] Algorithms working with wheel encoders
- [ ] Algorithms working with 2D vision, both looking forward and downward
- [ ] Algorithms working with various radio waves
- [ ] The entire algorithm pipeline from data reading to path planning

What it must include:
- [ ] A brief introduction to what this field is and what it offers us
- [ ] Description of the technologies
- [ ] Advantages and disadvantages of the solutions (preferably in a table)
- [ ] Opinion on which will be the best for us, considering:
	- [ ] Difficulty of implementation
	- [ ] Benefits
	- [ ] Scalability
	- [ ] Future usage

# Dependencies

- ROS 2 Humble
- Python 3
