### ISSUE TITLE
Research of reading, processing data

### ISSUE THREAD

**Issue by Kleczyk** [knmlprz/TrailblazerML#86]
# Description
The purpose of this is to review new techniques for reading data from the components we currently have and those we will need, such as the OAK camera, GPS, and RGB camera.

# Tasks
What the presentation should include:
- [ ] How data reading from these devices looks like
- [ ] How to implement this in ROS
- [ ] Whether and how to process this data

What it must include:
- [ ] A brief introduction to what this field is and what it offers us
- [ ] Description of the technologies
- [ ] Advantages and disadvantages of the solutions (preferably in a table)
- [ ] Opinion on which will be the best for us, considering:
	- [ ] Difficulty of implementation
	- [ ] Benefits
	- [ ] Scalability
	- [ ] Future use

# Dependencies

- ROS 2 Humble
- Python 3
