### ISSUE TITLE
Research of visualization

### ISSUE THREAD

**Issue by Kleczyk** [knmlprz/TrailblazerML#87]
# Description
The goal of this is to review new visualization techniques in ROS and beyond, which will be useful for our project. This should help us with debugging, controlling the rover, and testing new solutions both live and in simulation.

# Tasks
What the presentation should include:
- [ ] Visualization of the entire rover
- [ ] Visualization of odometry
- [ ] Visualization of the movement strategy map
- [ ] Visualization of readings from all sensors, etc.

What it must include:
- [ ] A brief introduction to what this field is and what it offers us
- [ ] Description of the technologies
- [ ] Advantages and disadvantages of the solutions (preferably in a table)
- [ ] Opinion on which will be the best for us, considering:
	- [ ] Difficulty of implementation
	- [ ] Benefits
	- [ ] Scalability
	- [ ] Future usage

# Dependencies

- ROS 2 Humble
- Python 3
