### ISSUE TITLE
Research of rover control

### ISSUE THREAD

**Issue by Kleczyk** [knmlprz/TrailblazerML#88]
# Description
The goal of this is to review new techniques for controlling a rover using a microcontroller like Arduino/ESP, etc., where micro-ROS will be running.

# Tasks
What the presentation should include:
- [ ] What micro-ROS is
- [ ] How to control motor PWM drivers
- [ ] How communication between Jetson and the microcontroller should work

What it must include:
- [ ] A brief introduction to what this field is and what it offers us
- [ ] Description of the technologies
- [ ] Advantages and disadvantages of the solutions (preferably in a table)
- [ ] Opinion on which will be the best for us, considering:
	- [ ] Difficulty of implementation
	- [ ] Benefits
	- [ ] Scalability
	- [ ] Future usage

# Dependencies

- ROS 2 Humble
- Python 3

**Comment by bafaurazan** [comment]
https://github.com/user-attachments/assets/4736d54f-82b9-416a-9a9a-3223f121e39e
