### ISSUE TITLE
Visualization and simulation

### ISSUE THREAD

**Issue by Kleczyk** [knmlprz/TrailblazerML#93]
# Description
In order to test without running the platform, we should create a simulation with an accurate model of the rover, which will allow us to collect data and test the system under near-real conditions.(suggested system gazebo)

To check if the system correctly visualization is necessary (suggested system RViz)

# Tasks
- [x] Prepare `.stl` files for the 3D model of the rover
- [x] Prepare the `.urdf` file
- [x] Other files
- [x] Launch `Gazebo` using the above files
- [x] Connect Gazebo with Rviz
    - [x] Select necessary parameters for monitoring
    - [x] Prepare topics for the real rover
- [x] Write README.md

# Possible Solution
Working Gazebo and RViz xd

# Dependencies
- .stl from legendary 

# Blocked by
None
