### ISSUE TITLE
First Nodes of Controller and Actuator

### ISSUE THREAD

**Issue by Kleczyk** [knmlprz/TrailblazerML#94]
# Description
To verify the system's functionality, it should be tested on a test platform with appropriate nodes for communication with elements outside of ROS and the autonomous system. Creating nodes for microcontroller communication and platform control is essential.

# Tasks
- [ ] Node for the controller
- [ ] Node for the actuator
- [x] Proper setup of micro-ROS on ESP32
- [x] Physical tests
- [ ] create software tests  

# Possible Solution

# Dependencies

- ROS 2 Humble
- micro-ROS
- freeRTOS

# Blocked by

**Comment by bafaurazan** [comment]
Uploading 20241013_204753.mp4…

Freertos, espressif, micro-ros, blink test
