### ISSUE TITLE
Reading data from sensor

### ISSUE THREAD

**Issue by Kleczyk** [knmlprz/TrailblazerML#96]
## Description
We need to implement sensor data readings in ROS for devices like OAK, GPS, and IMU. This data should be converted into ROS-supported types to ensure more efficient communication with other nodes.

## Tasks
- [ ] Propose the structure of a node system for sensor data reading #91 
- [ ] Select one sensor to begin implementation
- [ ] know about types data in [planers](#95 )
- [ ] Implement sensor data reading in ROS for integration with the path planner

## Possible Solution

Structure of few reading and transform nodes  

## Blocked by
